apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hw-nodejs 
  janus-idp.io/tekton: hw-nodejs
  backstage.io/kubernetes-id: hw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hw-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  